# Generated by Django 4.2.9 on 2024-01-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("assitantId", models.CharField(max_length=200)),
                ("threadID", models.CharField(max_length=200)),
            ],
        ),
    ]
