# Generated by Django 4.2.9 on 2024-01-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customBot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="assitantId",
            field=models.CharField(max_length=250),
        ),
    ]
